{{- if .Values.prometheusExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: htcondor-exporter-svc
  labels:
    app: htcondor-exporter
spec:
  type: NodePort
  ports:
  - port: 9118
    protocol: TCP
    targetPort: 9118
  selector:
    app: htcondor-exporter
{{- end }}