{{- if or .Values.master.enabled .Values.schedd.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: submission-endpoint
stringData:
  collector-url: "{{ .Values.master.publicIP }}.myip.cloud.infn.it:30618"
  schedd-url: "{{ .Values.master.publicIP }}.myip.cloud.infn.it"
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-key-pair
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDYTCCAkmgAwIBAgIUFMve/HdPx+phrbUyE+D2QIfhZD0wDQYJKoZIhvcNAQEL
    BQAwQDELMAkGA1UEBhMCSVQxEDAOBgNVBAgMB1BlcnVnaWExEDAOBgNVBAcMB1Bl
    cnVnaWExDTALBgNVBAoMBElORk4wHhcNMjEwNDI4MjAwODQ2WhcNMjYwNDI3MjAw
    ODQ2WjBAMQswCQYDVQQGEwJJVDEQMA4GA1UECAwHUGVydWdpYTEQMA4GA1UEBwwH
    UGVydWdpYTENMAsGA1UECgwESU5GTjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
    AQoCggEBANSbleWTYBJelH4QLJt6S0kSt7hh2l19IHLjA7qLt9y3RemZ+kNrL2Ha
    2glpCNH5Ggsrt0ThBTSsADcINjmFmCCWJ2TFBb+bcMTguaCWJwZNnyMXZQ5AYfbQ
    5b/J2jfhVRD7ED6RgSeDW5nBLhTChgvq48QhcYYFQ0UNaXBV8fSBnu08VGaLq/ab
    peym3NsOeR/h9raIXWzVtYGMRfuL8VpLzZ57GLmp1xRc4hp/DwIzw3erGaX0axvM
    tgKG8KMpi9VZGO3KiApa8i4eJfuTYlrFy4Y5GOv7dsm7unwg3jIB4LcBuib/DMTh
    mRtB6hD07xLwQ9W5rwX0LPiRqn/A65sCAwEAAaNTMFEwHQYDVR0OBBYEFOcwwtOE
    XF95HohEG588Qrg1ZKo3MB8GA1UdIwQYMBaAFOcwwtOEXF95HohEG588Qrg1ZKo3
    MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBACJ67Q96s3n8lvz+
    lhdJi+fTDsbfZrO7LwtbJ7K/GciBjUr00aaaAaKv9P1dbPlvWNiP0elP2f7Sww50
    kw3LnMz4okM3EcK2aXPIEgD9QzU8cSPmQMIHOBfPrQlFCTjYntaPpQ92WmRsdmD6
    QHGC94sscfX9hCx8WBKFoRgnQlEH1sgxApoq5R3/33YzwccHVfLOkNicta+oqh2b
    ZknTBraZwEz+xM109iA/fgXg1cRUXGV1FQIukRn+n8hjMPFVmXIocZSvTLDAWUmQ
    9FsLxJ3RCsknLk+y5U9cMofQ+FCPJfFtU8JHynz3Ofyh3zhsElosoUuBDiihph4T
    +Mu8MOY=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA1JuV5ZNgEl6UfhAsm3pLSRK3uGHaXX0gcuMDuou33LdF6Zn6
    Q2svYdraCWkI0fkaCyu3ROEFNKwANwg2OYWYIJYnZMUFv5twxOC5oJYnBk2fIxdl
    DkBh9tDlv8naN+FVEPsQPpGBJ4NbmcEuFMKGC+rjxCFxhgVDRQ1pcFXx9IGe7TxU
    Zour9pul7Kbc2w55H+H2tohdbNW1gYxF+4vxWkvNnnsYuanXFFziGn8PAjPDd6sZ
    pfRrG8y2AobwoymL1VkY7cqIClryLh4l+5NiWsXLhjkY6/t2ybu6fCDeMgHgtwG6
    Jv8MxOGZG0HqEPTvEvBD1bmvBfQs+JGqf8DrmwIDAQABAoIBAQCIUd4x3mX6QUSK
    9An2Atrk1qiQA8YEracxoteQM+fHEIg2OTFbKw2te6rT39H09/i38ubGtlUlKafV
    oWFLTpp1QnGtzhpaees7gS/khIIvK3P/BxAXrDZkEBtP9rgBnmxxv9jxlVAvqq0A
    D/pg+z0BxTEXX64vlY5FZ00U5zaFY6/pY827XQ0eugu+nKiRkzIkDoTzNf+8y9S5
    6bZDjMKED0iGKqB7FI2qzLnhtUYYMNbb2uuryP9CRNkyquLpfyK+YOXdqOSfNORo
    0h3LcpzjlytY2jgAZpusAYURbbxbVVQ13MWRob/kU58iEy2CmfQJ4FofiwFqnEVx
    i5jzgERBAoGBAO5nQdCctvuLXFso+D47U8hHkEJScMWS8sFCw4wWManjcUjz+up9
    xX6JOPlpbdiQsmgR7Syx6d6rlzeKgFmH5JBpby4HNkOnTGW+yNQMJPXQGsGwgpk6
    G/9YFgOCQKPWlNvX2WZG9bQijQDOForxxJ4M+lilFcMy3XuwZx4+frA7AoGBAORM
    6J19hwXejyn1w3jbZcqvwNm+bXBFei74LdMzhwtPoh6HFfvRFuy/Ab1ivrze8JNm
    Enz0yuWoJyThST9bvJtf/+WPf7RLNwcGE0VW2yMZW+zznCOHQqpQ6z0Ha4b43Lje
    1bJVBd7YOZXfXKK0MFGVtaiEh22iG/x9un9L1VwhAoGBAOvpWgNpUNlSaq36uMw8
    QQgraOF4WwfoBjigLIlvXO3Ul8GtTVrF4qz4dVy5q21momTBeIWF+PvTqOvZLnFq
    PA97hf1yPYxs/Pih9nF/IwPsTs3kMRgXnKTtMbt/JR/7s4po6kR/a5w5pHZreXs9
    C2erSAB4PDTRHMLNKP2QsiUJAoGAKop6Pf6KDnnuS29UQU0ApsghM3HcirMnlWEB
    iP1tCJqKJw4c9pN7phnhhRzFVgRk59J5V3d1511yDdk9AOVjO8Cjum8G6N2rH0/u
    f1kz9FJhYsHyMlyd+4agjvq2+quc1YYQY+6b7W51LIw2gsr4xfsTopcvdSpj9KSo
    /9dtpoECgYB99+1GPapyeYLi3aJjei+9/OBnqUk8O9VxpfkaLWV3nRSLoFsnHSAP
    FuO9sWWIH7NbVDWoQxueNWvrVdc6sC+FKIuJ6pnG/lKPt7G7GtYW7wnPOD7tRzD6
    UywE12fp36T/2wEzt4WhAI63HdQlRDwZGo1vpT2GoCEWnWsKvnhNDQ==
    -----END RSA PRIVATE KEY-----

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-key-pair
---
# define a CA to sign certificate
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-htc-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: htcondor-tls
spec:
  # Secret names are always required.
  secretName: htcondor-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - infn
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: {{ .Values.master.hostname }}
  isCA: False
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
  - {{ .Values.master.hostname }}
  - master.{{ .Release.Namespace }}.svc.cluster.local
  - "schedd.{{ .Release.Namespace }}.svc.cluster.local"
  ipAddresses:
    - {{ .Values.master.publicIP }}
  # Issuer references are always required.
  issuerRef:
    name: ca-issuer
    #name: self-htc-issuer
    kind: Issuer
    #name: letsencrypt-staging
    #kind: ClusterIssuer

{{- end }}